### PR TITLE
Fix: Move `fuzzy_search_items` to `utils` to resolve #820

### LINKED ISSUE #820: Cannot build with fzf since v0.21.0
**Describe the bug**
When trying to build with fzf this error is shown:

```
error[E0425]: cannot find function `fuzzy_search_items` in this scope
   --> /home/sam/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/spotify_player-0.21.0/src/utils.rs:61:12
    |
61  |     return fuzzy_search_items(items, &query);
    |            ^^^^^^^^^^^^^^^^^^ not found in this scope
    |
note: function `crate::state::ui::fuzzy_search_items` exists but is inaccessible
   --> /home/sam/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/spotify_player-0.21.0/src/state/ui/mod.rs:105:1
    |
105 | fn fuzzy_search_items<'a, T: std::fmt::Display>(items: &'a [T], query: &str) -> Vec<&'a T> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not accessible
```

If I drop fzf from the list of features it builds correctly.

**To Reproduce**

```bash
cargo install spotify_player --features image,pulseaudio-backend,fzf,streaming,media-control, --no-default-features --locked --force
```

**Expected behaviour**
Build correctly

**Log and backtrace**
Log and backtrace of a run reproducing the bug to help debug the issue, which are usually located in `$HOME/.cache/spotify-player/`.

Please refer to [this URL](https://github.com/aome510/spotify-player?tab=readme-ov-file#logging) for more details.

**Screenshots**

**Environment**

- OS: Fedora 42
- Application version: v0.21.0
- Rust version: rustc 1.89.0 (29483883e 2025-08-04) (Fedora 1.89.0-2.fc42)

### LINKED ISSUE #822: Build failure for 0.21.0
Hey, I'm trying to build and update the Arch Linux package as follows:

```
build() {
  local _features=('pulseaudio-backend' 'media-control' 'notify' 'daemon' 'image' 'sixel' 'fzf')
  cd "${pkgname}-${pkgver}"
  cargo build --frozen --release --bin spotify_player --no-default-features --features "${_features[*]}"
}
```

But getting this error:

```
   Compiling spotify_player v0.21.0 (/build/spotify-player/src/spotify-player-0.21.0/spotify_player)
error[E0425]: cannot find function `fuzzy_search_items` in this scope
   --> spotify_player/src/utils.rs:61:12
    |
61  |     return fuzzy_search_items(items, &query);
    |            ^^^^^^^^^^^^^^^^^^ not found in this scope
    |
note: function `crate::state::ui::fuzzy_search_items` exists but is inaccessible
   --> spotify_player/src/state/ui/mod.rs:105:1
    |
105 | fn fuzzy_search_items<'a, T: std::fmt::Display>(items: &'a [T], query: &str) -> Vec<&'a T> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not accessible

For more information about this error, try `rustc --explain E0425`.
error: could not compile `spotify_player` (bin "spotify_player") due to 1 previous error
==> ERROR: A failure occurred in build().
    Aborting...
```

Any ideas? 👀

### PR DESCRIPTION
**Pull request by Dragonfly911117**
- Relocated `fuzzy_search_items` from `ui::mod.rs` to `utils.rs` for the caller has been moved.
- Decoupled `ratatui::layout::Rect` import (`state/ui/mod.rs:100`) from the `fzf` feature gate since the dependent code(UIState::default()) does not rely on `fzf`.

- Fixes #820 
- Fixes #822 

Beside the issues mentioned, this patch also fixes building without `fzf` feature would fail due to `ratatui::layout::Rect` requiring `fzf` to be imported and `UIState::default()` was using it. The failing build log would look like
```text
> cargo run --bin spotify_player --no-default-features --features pulseaudio-backend,streaming,sixel,notify,daemon,media-control

=== bunch of log ===

error[E0433]: failed to resolve: use of undeclared type `Rect`
   --> spotify_player/src/state/ui/mod.rs:121:41
    |
121 |             playback_progress_bar_rect: Rect::default(),
    |                                         ^^^^ use of undeclared type `Rect`
    |
    = note: struct `crate::ui::utils::Rect` exists but is inaccessible
help: consider importing one of these structs
    |
1   + use image::math::Rect;
    |
1   + use ratatui::prelude::Rect;
    |
```

### CODE REVIEW

**Comment by aome510** [comment]
@Dragonfly911117, thanks for the PR. Can you also add `fzf` to a list of features in https://github.com/aome510/spotify-player/blob/e600c476ca7481eca0e8c6a81faa22d908314d2a/.github/workflows/ci.yml#L12 so that we don't fail to build in the future?

Actually I can just do it

**Review by aome510 — APPROVED** [review]

**Comment by PEKKA1117** [comment]
I've removed the redundant blank line. Please run the CI again.
