### ISSUE TITLE
cargo install fails to compile on Debian/rustc 1.81.0

### ISSUE THREAD

**Issue by ShuraShulgin** [aome510/spotify-player#571]
**Describe the bug**
error[E0308]: `match` arms have incompatible types appears if I try to install with cargo install spotify_player.

**To Reproduce**
1. Install fresh Debian 12 (bookworm) in WSL
2. Install Rust & dependencies like it has been described in the README
**Expected behaviour**
A successful installation

**Log and backtrace**
![image](https://github.com/user-attachments/assets/9e9811c4-2c8b-4d56-b236-1cc5b13bfb0f)

**Environment**

- OS: Debian 12 (bookworm) in WSL2
- Application version: well whatever cargo tries to install
- Application features: command: cargo install spotify_player

**Additional context**
I've had this working on my home machine and my work pc so I'm quite confused what is happening, I'm running the same script as I did on those machines, all the same setup (Debian 12 in WSL). Script is basically download neovim, download tmux, download rust, install dependencies, install spotify_player. If needed I can create a reduced version of the script just concerning the spotify_player part but that would take a second to extract all that.

**Comment by ManiArasteh** [comment]
I think it's WSL's problem. Install it within your Windows environment, not WSL

**Comment by ShuraShulgin** [comment]
> I think it's WSL's problem. Install it within your Windows environment, not WSL
That would defeat the usecase in my circumstance, so no. Also I have 2 different WSL instances on other machines were this works(as stated above) so it cannot be solely WSLs fault.
I'll try different feature flags and report back if something works.

**Comment by aome510** [comment]
Similar to see https://github.com/aome510/spotify-player/issues/560. See the discussion on how to resolve

**Comment by ShuraShulgin** [comment]
> Similar to #560. See the discussion on how to resolve

Thank you very much, this worked.

**Comment by ManiArasteh** [comment]
This issue should be closed. 
But I am not the author of this issue
Maybe @aome510 or @ShuraShulgin can close it

**Comment by ManiArasteh** [comment]
I think you can remove Cargo.lock and add it to .gitignore
